### ISSUE TITLE
Any plans to upgrade Specsy to recent JUnit 5 versions?

### ISSUE THREAD

**Issue by sbrannen** [luontola/specsy#2]
I noticed Specsy is still built against JUnit 5.0 M3.

Do you have any plans to upgrade to recent versions (e.g., JUnit 5.3.2 or the upcoming JUnit 5.4)?

**Comment by luontola** [comment]
Thanks for notifying about that. I've been the last few years only in legacy (Java 7) and Clojure projects, so I haven't been following JUnit 5. 😆 I've now upgraded Specsy 2.3.3 to JUnit 5.3.2.

I'll still need to look at how `org.junit.jupiter.api.DynamicTest` and `org.junit.jupiter.api.DynamicContainer` do dynamic test registration, because IDEA shows them correctly but not Specsy's tests.

**Comment by sbrannen** [comment]
> Thanks for notifying about that. I've been the last few years only in legacy (Java 7) and Clojure projects, so I haven't been following JUnit 5. 😆 I've now upgraded Specsy 2.3.3 to JUnit 5.3.2.

Nice!

> I'll still need to look at how `org.junit.jupiter.api.DynamicTest` and `org.junit.jupiter.api.DynamicContainer` do dynamic test registration, because IDEA shows them correctly but not Specsy's tests.

That occurs here:

https://github.com/junit-team/junit5/blob/master/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/descriptor/TestFactoryTestDescriptor.java#L99

And the implementation of `dynamicTestExecutor::execute` is here: 

https://github.com/junit-team/junit5/blob/master/junit-platform-engine/src/main/java/org/junit/platform/engine/support/hierarchical/NodeTestTask.java#L165
